baseURL      = "https://fitfusiongame.cc/"
languageCode = "en-us"
title        = "FitFusion Game"
theme        = "LucentLink-Hugo"
minVersion   = "0.115.0"

[params]
  description     = "A simple, customizable, and responsive Linktree-style landing page built using Hugo, Tailwind CSS, and Font Awesome."
  googleAnalytics = "" 

[outputs]
  home = ["HTML"]
